spring:
  application:
    name: config-server
server:
  port: 0

management:
  context-path: /admin

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'

---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/destinyliu/spring-cloud-config-repo
          basedir: target/config

---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/